[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Powered by <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[ch]
  languageName = "Chinese"
  contentDir = "content/ch"
  weight = 20
  [ch.params]
    languageISO = "ZH"
    languageTag = "ZH-Hans"
    footer = '由<a class="text-muted" href="https://gethyas.com/">Hyas</a>驱动'
    alertText = 'Introductie van het Doks-kinderthema, verschillende DX + UX-updates en meer! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.2/">Bekijk Doks v0.2</a>'
