name: RROS website CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup node@v20.8
      uses: actions/setup-node@v3
      with:
        node-version: '20.8.0'

    - name: Install dependencies
      run: npm ci

    - name: Run linters
      run: npm run lint --if-present

    - name: Build site
      run: |
            node_modules/.bin/hugo/hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"      

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./public

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action