name: RROS website CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup node@v19.7.0
      uses: actions/setup-node@v3
      with:
        node-version: '19.7.0'

    - name: Install dependencies
      run: npm ci

    - name: Run linters
      run: npm run lint --if-present

    - name: Build site
      run: npm run build
